#!/usr/bin/env php
<?php
require __DIR__ . '/vendor/autoload.php';

use Dotenv\Dotenv;
use Src\CLI\CommandRunner;

if (file_exists(__DIR__ . '/.env')) {
    $dotenv = Dotenv::createImmutable(__DIR__);
    $dotenv->load();
}

$argv = $_SERVER['argv'] ?? [];
array_shift($argv); // remove o nome do script

$runner = new CommandRunner();
exit($runner->run($argv));
