#!/usr/bin/env php
<?php
/**
 * Sweflow CLI
 *
 * Uso:
 *   php sweflow migrate [--seed] [--rollback]
 *   php sweflow make:module NomeModulo
 *   php sweflow make:plugin NomePlugin
 *   php sweflow plugin:migrate
 *   php sweflow plugin:rollback [plugin]
 *   php sweflow setup
 */

require __DIR__ . '/vendor/autoload.php';

if (file_exists(__DIR__ . '/.env')) {
    $dotenv = Dotenv\Dotenv::createImmutable(__DIR__);
    $dotenv->load();
}

(new Src\CLI\CommandRunner())->run(array_slice($argv, 1));
